### ISSUE TITLE
Document output directory

### ISSUE THREAD

**Issue by fernandoacorreia** [ryankennedy/swagger-jaxrs-doclet#1]
Currently the files are being saved in a directory such as "target\classes\apidocs". It would be interesting to document this in the README, along with instructions on where to put them so Jetty will serve them.

**Comment by ryankennedy** [comment]
Agreed, I'd also like to add a parameter to the Doclet so the caller can specify an alternative location.

**Comment by rgahagan** [comment]
I just added
addBundle(new AssetsBundle("/apidocs/"));
addBundle(new AssetsBundle("/swagger-ui-1.1.0/", "/swagger-ui"));

to my service after downloading that version of the swagger ui and placing it in the resources dir.

Now the structure of the service.json is my problem, though, as it's referencing the resource json files in a sub-dir 'descriptors' instead of the root dir they get created in.

**Comment by ESPNMichaelKidd** [comment]
I believe this has been fixed along the way...

**Comment by ESPNMichaelKidd** [comment]
was fixed by #4, should be closed
